# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "技术"
 pageRef = "tech"
 weight = 10

[[main]]
 name = "LLM"
 pageRef = "tech/llm"
 parent = "技术"
 weight = 10

[[main]]
 name = "CUDA"
 pageRef = "tech/cuda"
 parent = "技术"
 weight = 20

[[main]]
 name = "算法"
 pageRef = "tech/algorithm"
 parent = "技术"
 weight = 40

[[main]]
 name = "PyTorch"
 pageRef = "tech/pytorch"
 parent = "技术"
 weight = 20

[[main]]
 name = "生活"
 pageRef = "life"
 weight =20

[[main]]
 name = "活动"
 pageRef = "life/events"
 parent = "生活"
 weight = 20

[[main]]
 name = "旅行"
 pageRef = "life/travel"
 parent = "生活"
 weight = 30

[[main]]
 name = "金融"
 pageRef = "finance"
 weight = 30

[[main]]
 name = "系列"
 pageRef = "series"
 weight = 50

[[main]]
 name = "标签"
 pageRef = "tags"
 weight = 60

[[main]]
 name = "作者"
 pageRef = "about"
 weight = 100

# [[main]]
#   pre = "github"
#   name = "GitHub"
#   url = "https://github.com/chzhyang/"
#   weight = 100

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#    name = "Authors"
#    pageRef = "authors"
#    weight = 20
# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
